# Dockerfile
#
# Multi-stage build: separates the build environment from the runtime environment.
#
# STAGE 1 (deps):    Install ALL dependencies (including devDependencies)
# STAGE 2 (builder): Build the Next.js app
# STAGE 3 (runner):  Production image — only the runtime artifacts, no build tools
#
# Multi-stage builds result in much smaller images because node_modules,
# TypeScript compiler, etc. don't end up in the final image.

# ─── Stage 1: Install dependencies ────────────────────────────────────────
FROM node:20-alpine AS deps

# Install libc compatibility for Alpine (required by some native Node modules)
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy ONLY package files first.
# Docker caches each layer — if these files don't change, the
# expensive `npm ci` step is skipped on subsequent builds.
COPY package.json package-lock.json ./
COPY prisma ./prisma/

# npm ci is preferred over npm install in CI/Docker:
# - Uses the exact versions from package-lock.json
# - Fails if package-lock.json is out of sync
# - Does not update package-lock.json
RUN npm ci

# ─── Stage 2: Build the application ───────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

# Copy deps from previous stage (avoids reinstalling)
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate the Prisma Client before building Next.js
# This is required because Next.js imports Prisma at build time
RUN npx prisma generate

# Build the Next.js application
# Produces the .next/ folder with the optimized production build
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# ─── Stage 3: Production runner ────────────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user for security
# Running as root in production is a security risk — if the container is
# compromised, the attacker has root access to the container filesystem
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy only what's needed to run the app
# Standalone output mode (configured in next.config.js) copies all dependencies
# into .next/standalone, making the image smaller and self-contained
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

# Copy Next.js standalone build output
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is the standalone Next.js server — generated by the standalone output
CMD ["node", "server.js"]
