// src/types/index.ts
//
// Global TypeScript types shared across the application.
// These extend or supplement the types auto-generated by Prisma.

import type { Task, User, TaskStatus } from '@prisma/client'

// ─── API Response Types ────────────────────────────────────────────────────
// These represent what the API actually returns (may differ from raw DB models
// because of included relations, omitted fields, etc.)

// Task with optional user relation included
export type TaskWithUser = Task & {
  user: Pick<User, 'id' | 'name' | 'email'> | null
}

// User with task count (used in the users list endpoint)
export type UserWithTaskCount = User & {
  _count: { tasks: number }
}

// User with their tasks (used in the single user endpoint)
export type UserWithTasks = User & {
  tasks: Task[]
}

// ─── API Error Response ────────────────────────────────────────────────────
// Consistent error shape across all API routes
export interface ApiError {
  error: string
  details?: Record<string, string[]> // field-level validation errors from Zod
}

// ─── Re-exports ────────────────────────────────────────────────────────────
// Re-export Prisma types so the rest of the app only needs to import from @/types
export type { Task, User, TaskStatus }
